function plotBpsk()
% Function to plot BPSK modulation.
% bitstream
% 000001011011100100111101

clc; close all;

[LINEWIDTH, FONTSIZE, FONTNAME, LINECOLOR] = parameters();

FREQ = 4;

% plot symbols
k = linspace(0,4*pi);
PLOT_1 = cos(k + 1*pi/2);
PLOT_2 = cos(k + 3*pi/2);

figure;
tiledlayout(1,2);
PLOTS = {PLOT_1, PLOT_2};
for i = 1:length(PLOTS)
    nexttile;
    plot(PLOTS{i}, 'LineWidth', LINEWIDTH, 'color', LINECOLOR);
    title(dec2bin(i - 1));
    ylim([-1 1]);
    set(gca, 'XTick', [], 'FontSize', FONTSIZE, 'FontName', FONTNAME);
    yticks([-1 0 1]);
    set(gca, 'YGrid', 'on', 'XGrid', 'off');
    yticklabels({'-A_c', '0', 'A_c'});
end

% plot modulation
syms x;
y = piecewise( ...
    0 <= x < 5, sin(-FREQ*(x-0)*pi), ...
    5 <= x < 6, sin(FREQ*(x-5)*pi), ...
    6 <= x < 7, sin(-FREQ*(x-6)*pi), ...
    7 <= x < 9, sin(FREQ*(x-7)*pi), ...
    9 <= x < 10, sin(-FREQ*(x-9)*pi), ...
    10 <= x < 13, sin(FREQ*(x-10)*pi), ...
    13 <= x < 15, sin(-FREQ*(x-13)*pi), ...
    15 <= x < 16, sin(FREQ*(x-15)*pi), ...
    16 <= x < 18, sin(-FREQ*(x-16)*pi), ...
    18 <= x < 22, sin(FREQ*(x-18)*pi), ...
    22 <= x < 23, sin(-FREQ*(x-22)*pi), ...
    23 <= x <= 24, sin(FREQ*(x-23)*pi) ...
    );

figure;
fplot(y, 'LineWidth', LINEWIDTH, 'color', LINECOLOR);
ylim([-1 1]);
xlim([0 24]);
set(gca, 'YGrid', 'off', 'XGrid', 'on');
yticks([-1 0 1]);
xticks((1:24));
yticklabels({'-A_c', '0', 'A_c'});
xticklabels({ ...
    '0','0','0', ...
    '0','0','1', ...
    '0','1','1', ...
    '0','1','1', ...
    '1','0','0', ...
    '1','0','0', ...
    '1','1','1', ...
    '1','0','1', ...
    });
set(gca, 'FontSize', FONTSIZE, 'FontName', FONTNAME);
end