function plotPulses()
% Function to plot the pulses that correspond to a bit sequence.
% bitstream
% 000001011011100100111101

clc; close all;

[LINEWIDTH, FONTSIZE, FONTNAME, LINECOLOR] = parameters();

SEND_0 = 0;
SEND_1 = 1;

% % ===========
% % PLOT PULSES
syms x;
y = piecewise( ...
    0 <= x < 5, SEND_0, ...
    5 <= x < 6, SEND_1, ...
    6 <= x < 7, SEND_0, ...
    7 <= x < 9, SEND_1, ...
    9 <= x < 10, SEND_0, ...
    10 <= x < 13, SEND_1, ...
    13 <= x < 15, SEND_0, ...
    15 <= x < 16, SEND_1, ...
    16 <= x < 18, SEND_0, ...
    18 <= x < 22, SEND_1, ...
    22 <= x < 23, SEND_0, ...
    23 <= x <= 24, SEND_1 ...
    );

figure;
fplot(y, 'LineWidth', LINEWIDTH, 'color', LINECOLOR);
ylim([0 1]);
xlim([0 24]);
set(gca, 'YGrid', 'off', 'XGrid', 'on');
yticks([0 1]);
xticks((1:24));
yticklabels({'Low Voltage', 'High Voltage'});
xticklabels({ ...
    '0','0','0', ...
    '0','0','1', ...
    '0','1','1', ...
    '0','1','1', ...
    '1','0','0', ...
    '1','0','0', ...
    '1','1','1', ...
    '1','0','1', ...
    });
set(gca, 'FontSize', FONTSIZE, 'FontName', FONTNAME);
end